# Generated by Django 4.0.5 on 2022-07-05 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='-', max_length=25)),
                ('apellido', models.CharField(default='Dato privado', max_length=25)),
                ('birth_date', models.DateField()),
                ('edad', models.IntegerField()),
                ('ocupacion', models.CharField(default='No se especifica', max_length=25)),
                ('p', models.CharField(default='No se especifica parentezco', max_length=15)),
            ],
        ),
    ]
